# Pull base image
FROM ubuntu:latest

# File Author / Maintainer
MAINTAINER Jimmy Gong <gong.jim@gmail.com>

RUN sudo apt-get update
RUN sudo apt-get install -y python3-pip \
                            libpq-dev
